name: Upload Nonexistent Directory Test

on:
  workflow_dispatch:

jobs:
  test-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (just standard)
        uses: actions/checkout@v4

      - name: Upload non-existent folder
        uses: actions/upload-artifact@v4
        with:
          name: test-empty
          path: ./nonexistent-folder/**
          if-no-files-found: ignore
