name: Script 3

on:
  workflow_call:
    inputs:
      env-vars:
        type: string
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Reflect Env Propagation
        run: 
          # Generic propagation of environment variables
          echo "---- env-vars ----"
          echo "${{ inputs.env-vars }}"  
