name: Script 2

on:
  workflow_call:
    inputs:
      env-vars:
        type: string
        default: ""

jobs:
  run:
    uses: tryptamic/action-test/.github/workflows/script3.yaml@master
    with:
      env-vars: ${{ inputs.env-vars }}
