name: Script 1

on:
  workflow_dispatch:

jobs:
  run:
    uses: tryptamic/action-test/.github/workflows/script2.yaml@main
    env:
      ENV_VARS: |
        -- FOOBAR=${{ secrets.TEST_SECRET }}